// QS 2024 世界大学排名前200数据
// 基于权威的QS世界大学排名，包含排名、名称、中文名、国家/地区、校徽路径等信息

const QS_TOP_UNIVERSITIES = [
    { rank: 1, name: "Massachusetts Institute of Technology", chineseName: "麻省理工学院", country: "美国", logo: "image/global-universities/Massachusetts_Institute_of_Technology.png" },
    { rank: 2, name: "Imperial College London", chineseName: "伦敦帝国学院", country: "英国", logo: "image/global-universities/Imperial_College_London.png" },
    { rank: 3, name: "Stanford University", chineseName: "斯坦福大学", country: "美国", logo: "image/global-universities/Stanford_University.png" },
    { rank: 4, name: "University of Oxford", chineseName: "牛津大学", country: "英国", logo: "image/global-universities/University_of_Oxford.png" },
    { rank: 5, name: "Harvard University", chineseName: "哈佛大学", country: "美国", logo: "image/global-universities/Harvard_University.png" },
    { rank: 6, name: "University of Cambridge", chineseName: "剑桥大学", country: "英国", logo: "image/global-universities/University_of_Cambridge.png" },
    { rank: 7, name: "ETH Zurich", chineseName: "苏黎世联邦理工学院", country: "瑞士", logo: "image/global-universities/ETH_Zurich.png" },
    { rank: 8, name: "National University of Singapore", chineseName: "新加坡国立大学", country: "新加坡", logo: "image/global-universities/National_University_of_Singapore.png" },
    { rank: 9, name: "University College London", chineseName: "伦敦大学学院", country: "英国", logo: "image/global-universities/University_College_London.png" },
    { rank: 10, name: "California Institute of Technology", chineseName: "加州理工学院", country: "美国", logo: "image/global-universities/California_Institute_of_Technology.png" },
    { rank: 11, name: "The University of Hong Kong", chineseName: "香港大学", country: "中国香港", logo: "image/global-universities/The_University_of_Hong_Kong.png" },
    { rank: 12, name: "Nanyang Technological University", chineseName: "南洋理工大学", country: "新加坡", logo: "image/global-universities/Nanyang_Technological_University.png" },
    { rank: 13, name: "University of Chicago", chineseName: "芝加哥大学", country: "美国", logo: "image/global-universities/University_of_Chicago.png" },
    { rank: 14, name: "Peking University", chineseName: "北京大学", country: "中国", logo: "image/global-universities/Peking_University.png" },
    { rank: 15, name: "University of Pennsylvania", chineseName: "宾夕法尼亚大学", country: "美国", logo: "image/global-universities/University_of_Pennsylvania.png" },
    { rank: 16, name: "Cornell University", chineseName: "康奈尔大学", country: "美国", logo: "image/global-universities/Cornell_University.png" },
    { rank: 17, name: "Tsinghua University", chineseName: "清华大学", country: "中国", logo: "image/global-universities/Tsinghua_University.png" },
    { rank: 17, name: "University of California, Berkeley", chineseName: "加州大学伯克利分校", country: "美国", logo: "image/global-universities/University_of_California_Berkeley.png" },
    { rank: 19, name: "University of Melbourne", chineseName: "墨尔本大学", country: "澳大利亚", logo: "image/global-universities/University_of_Melbourne.png" },
    { rank: 20, name: "The University of New South Wales", chineseName: "新南威尔士大学", country: "澳大利亚", logo: "image/global-universities/The_University_of_New_South_Wales.png" },
    { rank: 21, name: "Yale University", chineseName: "耶鲁大学", country: "美国", logo: "image/global-universities/Yale_University.png" },
    { rank: 22, name: "Technical University of Munich", chineseName: "慕尼黑技术大学", country: "德国", logo: "image/global-universities/Technical_University_of_Munich.png" },
    { rank: 22, name: "École Polytechnique Fédérale de Lausanne", chineseName: "洛桑联邦理工学院", country: "瑞士", logo: "image/global-universities/École_Polytechnique_Fédérale_de_Lausanne.png" },
    { rank: 24, name: "Johns Hopkins University", chineseName: "约翰霍普金斯大学", country: "美国", logo: "image/global-universities/Johns_Hopkins_University.png" },
    { rank: 25, name: "Princeton University", chineseName: "普林斯顿大学", country: "美国", logo: "image/global-universities/Princeton_University.png" },
    { rank: 25, name: "The University of Sydney", chineseName: "悉尼大学", country: "澳大利亚", logo: "image/global-universities/The_University_of_Sydney.png" },
    { rank: 27, name: "McGill University", chineseName: "麦吉尔大学", country: "加拿大", logo: "image/global-universities/McGill_University.png" },
    { rank: 28, name: "PSL University", chineseName: "巴黎文理研究大学", country: "法国", logo: "image/global-universities/PSL_University.png" },
    { rank: 29, name: "University of Toronto", chineseName: "多伦多大学", country: "加拿大", logo: "image/global-universities/University_of_Toronto.png" },
    { rank: 30, name: "Fudan University", chineseName: "复旦大学", country: "中国", logo: "image/global-universities/Fudan_University.png" },
    { rank: 31, name: "King's College London", chineseName: "伦敦国王学院", country: "英国", logo: "image/global-universities/Kings_College_London.png" },
    { rank: 32, name: "Chinese University Hong Kong", chineseName: "香港中文大学", country: "中国香港", logo: "image/global-universities/Chinese_University_Hong_Kong.png" },
    { rank: 32, name: "The Australian National University", chineseName: "澳大利亚国立大学", country: "澳大利亚", logo: "image/global-universities/The_Australian_National_University.png" },
    { rank: 34, name: "The University of Edinburgh", chineseName: "爱丁堡大学", country: "英国", logo: "image/global-universities/The_University_of_Edinburgh.png" },
    { rank: 35, name: "The University of Manchester", chineseName: "曼彻斯特大学", country: "英国", logo: "image/global-universities/The_University_of_Manchester.png" },
    { rank: 36, name: "Monash University", chineseName: "蒙纳士大学", country: "澳大利亚", logo: "image/global-universities/Monash_University.png" },
    { rank: 36, name: "The University of Tokyo", chineseName: "东京大学", country: "日本", logo: "image/global-universities/The_University_of_Tokyo.png" },
    { rank: 38, name: "Seoul National University", chineseName: "首尔国立大学", country: "韩国", logo: "image/global-universities/Seoul_National_University.png" },
    { rank: 38, name: "Columbia University", chineseName: "哥伦比亚大学", country: "美国", logo: "image/global-universities/Columbia_University.png" },
    { rank: 40, name: "University of British Columbia", chineseName: "不列颠哥伦比亚大学", country: "加拿大", logo: "image/global-universities/University_of_British_Columbia.png" },
    { rank: 41, name: "Institut Polytechnique de Paris", chineseName: "巴黎理工学院", country: "法国", logo: "image/global-universities/Institut_Polytechnique_de_Paris.png" },
    { rank: 42, name: "Northwestern University", chineseName: "西北大学", country: "美国", logo: "image/global-universities/Northwestern_University.png" },
    { rank: 42, name: "The University of Queensland", chineseName: "昆士兰大学", country: "澳大利亚", logo: "image/global-universities/The_University_of_Queensland.png" },
    { rank: 44, name: "The Hong Kong University of Science and Technology", chineseName: "香港科技大学", country: "中国香港", logo: "image/global-universities/The_Hong_Kong_University_of_Science_and_Technology.png" },
    { rank: 45, name: "University of Michigan - Ann Arbor", chineseName: "密歇根大学安娜堡分校", country: "美国", logo: "image/global-universities/University_of_Michigan_Ann_Arbor.png" },
    { rank: 46, name: "University of California, Los Angeles", chineseName: "加州大学洛杉矶分校", country: "美国", logo: "image/global-universities/University_of_California_Los_Angeles.png" },
    { rank: 47, name: "Delft University of Technology", chineseName: "代尔夫特理工大学", country: "荷兰", logo: "image/global-universities/Delft_University_of_Technology.png" },
    { rank: 47, name: "Shanghai Jiao Tong University", chineseName: "上海交通大学", country: "中国", logo: "image/global-universities/Shanghai_Jiao_Tong_University.png" },
    { rank: 49, name: "Zhejiang University", chineseName: "浙江大学", country: "中国", logo: "image/global-universities/Zhejiang_University.png" },
    { rank: 50, name: "Yonsei University", chineseName: "延世大学", country: "韩国", logo: "image/global-universities/Yonsei_University.png" },
    { rank: 51, name: "University of Bristol", chineseName: "布里斯托大学", country: "英国", logo: "image/global-universities/University_of_Bristol.png" },
    { rank: 52, name: "Carnegie Mellon University", chineseName: "卡内基梅隆大学", country: "美国", logo: "image/global-universities/Carnegie_Mellon_University.png" },
    { rank: 53, name: "University of Amsterdam", chineseName: "阿姆斯特丹大学", country: "荷兰", logo: "image/global-universities/University_of_Amsterdam.png" },
    { rank: 54, name: "The Hong Kong Polytechnic University", chineseName: "香港理工大学", country: "中国香港", logo: "image/global-universities/The_Hong_Kong_Polytechnic_University.png" },
    { rank: 55, name: "New York University", chineseName: "纽约大学", country: "美国", logo: "image/global-universities/New_York_University.png" },
    { rank: 56, name: "London School of Economics and Political Science", chineseName: "伦敦政治经济学院", country: "英国", logo: "image/global-universities/London_School_of_Economics_and_Political_Science.png" },
    { rank: 57, name: "Kyoto University", chineseName: "京都大学", country: "日本", logo: "image/global-universities/Kyoto_University.png" },
    { rank: 58, name: "LMU Munich", chineseName: "慕尼黑大学", country: "德国", logo: "image/global-universities/LMU_Munich.png" },
    { rank: 58, name: "University of Malaya", chineseName: "马来亚大学", country: "马来西亚", logo: "image/global-universities/University_of_Malaya.png" },
    { rank: 60, name: "KU Leuven", chineseName: "鲁汶大学", country: "比利时", logo: "image/global-universities/KU_Leuven.png" },
    { rank: 61, name: "Korea University", chineseName: "高丽大学", country: "韩国", logo: "image/global-universities/Korea_University.png" },
    { rank: 62, name: "Duke University", chineseName: "杜克大学", country: "美国", logo: "image/global-universities/Duke_University.png" },
    { rank: 63, name: "City University Hong Kong", chineseName: "香港城市大学", country: "中国香港", logo: "image/global-universities/City_University_Hong_Kong.png" },
    { rank: 63, name: "National Taiwan University", chineseName: "国立台湾大学", country: "中国台湾", logo: "image/global-universities/National_Taiwan_University.png" },
    { rank: 65, name: "The University of Auckland", chineseName: "奥克兰大学", country: "新西兰", logo: "image/global-universities/The_University_of_Auckland.png" },
    { rank: 66, name: "University of California, San Diego", chineseName: "加州大学圣地亚哥分校", country: "美国", logo: "image/global-universities/University_of_California_San_Diego.png" },
    { rank: 67, name: "King Fahd University of Petroleum & Minerals", chineseName: "法赫德国王石油与矿产大学", country: "沙特阿拉伯", logo: "image/global-universities/King_Fahd_University_of_Petroleum_Minerals.png" },
    { rank: 68, name: "The University of Texas at Austin", chineseName: "德克萨斯大学奥斯汀分校", country: "美国", logo: "image/global-universities/The_University_of_Texas_at_Austin.png" },
    { rank: 69, name: "Brown University", chineseName: "布朗大学", country: "美国", logo: "image/global-universities/Brown_University.png" },
    { rank: 70, name: "Université Paris-Saclay", chineseName: "巴黎萨克雷大学", country: "法国", logo: "image/global-universities/Université_Paris_Saclay.png" },
    { rank: 70, name: "University of Illinois at Urbana-Champaign", chineseName: "伊利诺伊大学香槟分校", country: "美国", logo: "image/global-universities/University_of_Illinois_at_Urbana_Champaign.png" },
    { rank: 72, name: "Lund University", chineseName: "隆德大学", country: "瑞典", logo: "image/global-universities/Lund_University.png" },
    { rank: 72, name: "Sorbonne Universite", chineseName: "索邦大学", country: "法国", logo: "image/global-universities/Sorbonne_Universite.png" },
    { rank: 74, name: "University of Warwick", chineseName: "华威大学", country: "英国", logo: "image/global-universities/University_of_Warwick.png" },
    { rank: 75, name: "Trinity College Dublin", chineseName: "都柏林圣三一学院", country: "爱尔兰", logo: "image/global-universities/Trinity_College_Dublin.png" },
    { rank: 76, name: "University of Birmingham", chineseName: "伯明翰大学", country: "英国", logo: "image/global-universities/University_of_Birmingham.png" },
    { rank: 77, name: "The University of Western Australia", chineseName: "西澳大利亚大学", country: "澳大利亚", logo: "image/global-universities/The_University_of_Western_Australia.png" },
    { rank: 78, name: "KTH Royal Institute of Technology", chineseName: "瑞典皇家理工学院", country: "瑞典", logo: "image/global-universities/KTH_Royal_Institute_of_Technology.png" },
    { rank: 79, name: "University of Glasgow", chineseName: "格拉斯哥大学", country: "英国", logo: "image/global-universities/University_of_Glasgow.png" },
    { rank: 80, name: "Heidelberg University", chineseName: "海德堡大学", country: "德国", logo: "image/global-universities/Heidelberg_University.png" },
    { rank: 81, name: "University of Washington", chineseName: "华盛顿大学", country: "美国", logo: "image/global-universities/University_of_Washington.png" },
    { rank: 82, name: "Pennsylvania State University", chineseName: "宾夕法尼亚州立大学", country: "美国", logo: "image/global-universities/Pennsylvania_State_University.png" },
    { rank: 84, name: "Universidad de Buenos Aires", chineseName: "布宜诺斯艾利斯大学", country: "阿根廷", logo: "" },
    { rank: 85, name: "Tokyo Institute of Technology", chineseName: "东京工业大学", country: "日本", logo: "image/global-universities/Tokyo_Institute_of_Technology.png" },
    { rank: 86, name: "University of Leeds", chineseName: "利兹大学", country: "英国", logo: "image/global-universities/University_of_Leeds.png" },
    { rank: 87, name: "University of Southampton", chineseName: "南安普顿大学", country: "英国", logo: "image/global-universities/University_of_Southampton.png" },
    { rank: 88, name: "Boston University", chineseName: "波士顿大学", country: "美国", logo: "image/global-universities/Boston_University.png" },
    { rank: 88, name: "Freie Universität Berlin", chineseName: "柏林自由大学", country: "德国", logo: "image/global-universities/Freie_Universität_Berlin.png" },
    { rank: 88, name: "Purdue University", chineseName: "普渡大学", country: "美国", logo: "image/global-universities/Purdue_University.png" },
    { rank: 91, name: "The University of Osaka", chineseName: "大阪大学", country: "日本", logo: "image/global-universities/The_University_of_Osaka.png" },
    { rank: 92, name: "The University of Sheffield", chineseName: "谢菲尔德大学", country: "英国", logo: "image/global-universities/The_University_of_Sheffield.png" },
    { rank: 93, name: "Uppsala University", chineseName: "乌普萨拉大学", country: "瑞典", logo: "image/global-universities/Uppsala_University.png" },
    { rank: 94, name: "Durham University", chineseName: "杜伦大学", country: "英国", logo: "image/global-universities/Durham_University.png" },
    { rank: 94, name: "University of Alberta", chineseName: "阿尔伯塔大学", country: "加拿大", logo: "image/global-universities/University_of_Alberta.png" },
    { rank: 96, name: "University of Technology Sydney", chineseName: "悉尼科技大学", country: "澳大利亚", logo: "image/global-universities/University_of_Technology_Sydney.png" },
    { rank: 97, name: "The University of Nottingham", chineseName: "诺丁汉大学", country: "英国", logo: "image/global-universities/The_University_of_Nottingham.png" },
    { rank: 98, name: "Karlsruhe Institute of Technology (KIT)", chineseName: "卡尔斯鲁厄理工学院", country: "德国", logo: "image/global-universities/Karlsruhe_Institute_of_Technology.png" },
    { rank: 98, name: "Politecnico di Milano", chineseName: "米兰理工大学", country: "意大利", logo: "image/global-universities/Politecnico_di_Milano.png" },
    { rank: 100, name: "University of Zurich (UZH)", chineseName: "苏黎世大学", country: "瑞士", logo: "image/global-universities/University_of_Zurich.png" },
    { rank: 101, name: "University of Copenhagen", chineseName: "哥本哈根大学", country: "丹麦", logo: "image/global-universities/University_of_Copenhagen.png" },
    { rank: 102, name: "Pohang University of Science And Technology (POSTECH)", chineseName: "浦项科技大学", country: "韩国", logo: "image/global-universities/Pohang_University_of_Science_and_Technology.png" },
    { rank: 103, name: "Nanjing University", chineseName: "南京大学", country: "中国", logo: "image/global-universities/Nanjing_University.png" },
    { rank: 103, name: "Utrecht University", chineseName: "乌特勒支大学", country: "荷兰", logo: "image/global-universities/Utrecht_University.png" },
    { rank: 105, name: "Lomonosov Moscow State University", chineseName: "罗蒙诺索夫莫斯科国立大学", country: "俄国", logo: "image/global-universities/Lomonosov_Moscow_State_University.png" },
    { rank: 105, name: "Rheinisch-Westfälische Technische Hochschule Aachen", chineseName: "亚琛莱茵-威斯特法伦工业大学", country: "德国", logo: "image/global-universities/Rheinisch_Westfälische_Technische_Hochschule_Aachen.png" },
    { rank: 107, name: "Technical University of Denmark", chineseName: "丹麦技术大学", country: "丹麦", logo: "image/global-universities/Technical_University_of_Denmark.png" },
    { rank: 108, name: "Universidade de São Paulo (USP)", chineseName: "圣保罗大学", country: "巴西", logo: "image/global-universities/Universidade_de_São_Paulo.png" },
    { rank: 109, name: "Tohoku University", chineseName: "东北大学", country: "日本", logo: "image/global-universities/Tohoku_University.png" },
    { rank: 110, name: "Queen Mary University of London (QMUL)", chineseName: "伦敦大学玛丽皇后学院", country: "英国", logo: "image/global-universities/Queen_Mary_University_of_London.png" },
    { rank: 110, name: "University of Wisconsin-Madison", chineseName: "威斯康星大学-麦迪逊", country: "美国", logo: "image/global-universities/University_of_Wisconsin_Madison.png" },
    { rank: 112, name: "Qatar University", chineseName: "卡塔尔大学", country: "卡塔尔", logo: "image/global-universities/Qatar_University.png" },
    { rank: 113, name: "University of St Andrews", chineseName: "圣安德鲁斯大学", country: "英国", logo: "image/global-universities/University_of_St_Andrews.png" },
    { rank: 114, name: "Aalto University", chineseName: "阿尔托大学", country: "芬兰", logo: "image/global-universities/Aalto_University.png" },
    { rank: 114, name: "University of California, Davis", chineseName: "加州大学戴维斯分校", country: "美国", logo: "image/global-universities/University_of_California_Davis.png" },
    { rank: 116, name: "Pontificia Universidad Católica de Chile", chineseName: "智利天主教大学", country: "智利", logo: "image/global-universities/Pontifical_Catholic_University_of_Chile.png" },
    { rank: 116, name: "University of Helsinki", chineseName: "赫尔辛基大学", country: "芬兰", logo: "image/global-universities/University_of_Helsinki.png" },
    { rank: 118, name: "University College Dublin", chineseName: "都柏林大学", country: "爱尔兰", logo: "image/global-universities/University_College_Dublin.png" },
    { rank: 119, name: "Leiden University", chineseName: "莱顿大学", country: "荷兰", logo: "image/global-universities/Leiden_University.png" },
    { rank: 119, name: "Rice University", chineseName: "莱斯大学", country: "美国", logo: "image/global-universities/Rice_University.png" },
    { rank: 119, name: "University of Oslo", chineseName: "奥斯陆大学", country: "挪威", logo: "image/global-universities/University_of_Oslo.png" },
    { rank: 119, name: "University of Waterloo", chineseName: "滑铁卢大学", country: "加拿大", logo: "image/global-universities/University_of_Waterloo.png" },
    { rank: 123, name: "Georgia Institute of Technology", chineseName: "佐治亚理工学院", country: "美国", logo: "image/global-universities/Georgia_Institute_of_Technology.png" },
    { rank: 123, name: "Indian Institute of Technology Delhi (IITD)", chineseName: "印度理工学院德里", country: "印度", logo: "image/global-universities/Indian_Institute_of_Technology_Delhi.png" },
    { rank: 125, name: "RMIT University", chineseName: "墨尔本皇家理工大学", country: "澳大利亚", logo: "image/global-universities/RMIT_University.png" },
    { rank: 126, name: "Sungkyunkwan University", chineseName: "成均馆大学", country: "韩国", logo: "image/global-universities/Sungkyunkwan_University.png" },
    { rank: 126, name: "Universiti Kebangsaan Malaysia (UKM)", chineseName: "马来西亚国民大学", country: "马来西亚", logo: "image/global-universities/Universiti_Kebangsaan_Malaysia.png" },
    { rank: 128, name: "Sapienza University of Rome", chineseName: "罗马大学", country: "意大利", logo: "image/global-universities/Sapienza_University_of_Rome.png" },
    { rank: 129, name: "Indian Institute of Technology Bombay (IITB)", chineseName: "印度理工学院孟买校区", country: "印度", logo: "image/global-universities/Indian_Institute_of_Technology_Bombay.png" },
    { rank: 130, name: "Humboldt-Universität zu Berlin", chineseName: "柏林洪堡大学", country: "德国", logo: "image/global-universities/Humboldt_Universität_zu_Berlin.png" },
    { rank: 131, name: "Aarhus University", chineseName: "奥胡斯大学", country: "丹麦", logo: "image/global-universities/Aarhus_University.png" },
    { rank: 132, name: "University of Bath", chineseName: "巴斯大学", country: "英国", logo: "image/global-universities/University_of_Bath.png" },
    { rank: 132, name: "University of Science and Technology of China", chineseName: "中国科学技术大学", country: "中国", logo: "image/global-universities/University_of_Science_and_Technology_of_China.png" },
    { rank: 134, name: "Universiti Putra Malaysia (UPM)", chineseName: "马来西亚博特拉大学", country: "马来西亚", logo: "image/global-universities/Universiti_Putra_Malaysia.png" },
    { rank: 134, name: "Universiti Sains Malaysia (USM)", chineseName: "马来西亚理科大学", country: "马来西亚", logo: "image/global-universities/Universiti_Sains_Malaysia.png" },
    { rank: 136, name: "Universidad Nacional Autónoma de México (UNAM)", chineseName: "墨西哥国立自治大学", country: "墨西哥", logo: "image/global-universities/Universidad_Nacional_Autónoma_de_México.png" },
    { rank: 137, name: "Newcastle University", chineseName: "纽卡斯尔大学", country: "英国", logo: "image/global-universities/Newcastle_University.png" },
    { rank: 138, name: "Alma Mater Studiorum - University of Bologna", chineseName: "博洛尼亚大学", country: "意大利", logo: "image/global-universities/Alma_Mater_Studiorum_University_of_Bologna.png" },
    { rank: 138, name: "Macquarie University", chineseName: "麦考瑞大学", country: "澳大利亚", logo: "image/global-universities/Macquarie_University.png" },
    { rank: 140, name: "Eindhoven University of Technology", chineseName: "埃因霍温科技大学", country: "荷兰", logo: "image/global-universities/Eindhoven_University_of_Technology.png" },
    { rank: 140, name: "Erasmus University Rotterdam", chineseName: "鹿特丹伊拉斯姆斯大学", country: "荷兰", logo: "image/global-universities/Erasmus_University_Rotterdam.png" },
    { rank: 140, name: "University of North Carolina, Chapel Hill", chineseName: "北卡罗来纳大学教堂山分校", country: "美国", logo: "image/global-universities/University_of_North_Carolina_Chapel_Hill.png" },
    { rank: 143, name: "King Saud University", chineseName: "沙特国王大学", country: "沙特阿拉伯", logo: "image/global-universities/King_Saud_University.png" },
    { rank: 144, name: "Texas A&M University", chineseName: "德州农工大学", country: "美国", logo: "image/global-universities/Texas_AM_University.png" },
    { rank: 145, name: "Technische Universität Berlin", chineseName: "柏林工业大学", country: "德国", logo: "image/global-universities/Technische_Universität_Berlin.png" },
    { rank: 146, name: "University of Southern California", chineseName: "南加州大学", country: "美国", logo: "image/global-universities/University_of_Southern_California.png" },
    { rank: 147, name: "Stockholm University", chineseName: "斯德哥尔摩大学", country: "瑞典", logo: "image/global-universities/Stockholm_University.png" },
    { rank: 147, name: "University of Groningen", chineseName: "格罗宁根大学", country: "荷兰", logo: "image/global-universities/University_of_Groningen.png" },
    { rank: 147, name: "University of Liverpool", chineseName: "利物浦大学", country: "英国", logo: "image/global-universities/University_of_Liverpool.png" },
    { rank: 150, name: "University of Cape Town", chineseName: "开普敦大学", country: "南非", logo: "image/global-universities/University_of_Cape_Town.png" },
    { rank: 151, name: "Western University", chineseName: "西安大略大学", country: "加拿大", logo: "image/global-universities/Western_University.png" },
    { rank: 152, name: "University of Vienna", chineseName: "维也纳大学", country: "奥地利", logo: "image/global-universities/University_of_Vienna.png" },
    { rank: 153, name: "Universiti Teknologi Malaysia (UTM)", chineseName: "马来西亚工艺大学", country: "马来西亚", logo: "image/global-universities/Universiti_Teknologi_Malaysia.png" },
    { rank: 153, name: "Wageningen University & Research", chineseName: "瓦赫宁根大学与研究院", country: "荷兰", logo: "image/global-universities/Wageningen_University_Research.png" },
    { rank: 155, name: "University of Exeter", chineseName: "埃克塞特大学", country: "英国", logo: "image/global-universities/University_of_Exeter.png" },
    { rank: 155, name: "University of Geneva", chineseName: "日内瓦大学", country: "瑞士", logo: "image/global-universities/University_of_Geneva.png" },
    { rank: 157, name: "Lancaster University", chineseName: "兰开斯特大学", country: "英国", logo: "image/global-universities/Lancaster_University.png" },
    { rank: 158, name: "University of Basel", chineseName: "巴塞尔大学", country: "瑞士", logo: "image/global-universities/University_of_Basel.png" },
    { rank: 159, name: "Hanyang University", chineseName: "汉阳大学", country: "韩国", logo: "image/global-universities/Hanyang_University.png" },
    { rank: 160, name: "University of Barcelona", chineseName: "巴塞罗那大学", country: "西班牙", logo: "image/global-universities/University_of_Barcelona.png" },
    { rank: 161, name: "Michigan State University", chineseName: "密歇根州立大学", country: "美国", logo: "image/global-universities/Michigan_State_University.png" },
    { rank: 162, name: "Ghent University", chineseName: "根特大学", country: "比利时", logo: "image/global-universities/Ghent_University.png" },
    { rank: 163, name: "King Abdul Aziz University (KAU)", chineseName: "阿卜杜勒阿齐兹国王大学", country: "沙特阿拉伯", logo: "image/global-universities/King_Abdul_Aziz_University.png" },
    { rank: 164, name: "Nagoya University", chineseName: "名古屋大学", country: "日本", logo: "image/global-universities/Nagoya_University.png" },
    { rank: 165, name: "Chalmers University of Technology", chineseName: "查尔姆斯理工大学", country: "瑞典", logo: "image/global-universities/Chalmers_University_of_Technology.png" },
    { rank: 166, name: "Al-Farabi Kazakh National University", chineseName: "阿尔-法拉比国立大学", country: "哈萨克斯坦", logo: "image/global-universities/Al_Farabi_Kazakh_National_University.png" },
    { rank: 167, name: "Washington University in St. Louis", chineseName: "圣路易斯华盛顿大学", country: "美国", logo: "image/global-universities/Washington_University_in_St_Louis.png" },
    { rank: 168, name: "University of Montreal", chineseName: "蒙特利尔大学", country: "加拿大", logo: "image/global-universities/University_of_Montreal.png" },
    { rank: 169, name: "University of York", chineseName: "约克大学", country: "英国", logo: "image/global-universities/University_of_York.png" },
    { rank: 170, name: "Hokkaido University", chineseName: "北海道大学", country: "日本", logo: "image/global-universities/Hokkaido_University.png" },
    { rank: 170, name: "Kyushu University", chineseName: "九州大学", country: "日本", logo: "image/global-universities/Kyushu_University.png" },
    { rank: 172, name: "Universitat Autónoma de Barcelona", chineseName: "巴塞罗那自治大学", country: "西班牙", logo: "image/global-universities/Universitat_Autónoma_de_Barcelona.png" },
    { rank: 173, name: "Arizona State University", chineseName: "亚利桑那州立大学", country: "美国", logo: "image/global-universities/Arizona_State_University.png" },
    { rank: 173, name: "McMaster University", chineseName: "麦克马斯特大学", country: "加拿大", logo: "image/global-universities/McMaster_University.png" },
    { rank: 173, name: "Universidad de Chile", chineseName: "智利大学", country: "智利", logo: "image/global-universities/Universidad_de_Chile.png" },
    { rank: 176, name: "National Tsing Hua University", chineseName: "国立清华大学", country: "中国台湾", logo: "image/global-universities/National_Tsing_Hua_University.png" },
    { rank: 177, name: "Khalifa University of Science and Technology", chineseName: "哈利法科技大学", country: "阿拉伯联合酋长国", logo: "image/global-universities/Khalifa_University_of_Science_and_Technology.png" },
    { rank: 177, name: "Tongji University", chineseName: "同济大学", country: "中国", logo: "image/global-universities/Tongji_University.png" },
    { rank: 179, name: "University of California, Santa Barbara (UCSB)", chineseName: "加州大学圣塔芭芭拉分校", country: "美国", logo: "image/global-universities/University_of_California_Santa_Barbara.png" },
    { rank: 180, name: "Indian Institute of Technology Madras (IITM)", chineseName: "印度理工学院马德拉斯校区", country: "印度", logo: "image/global-universities/Indian_Institute_of_Technology_Madras.png" },
    { rank: 181, name: "Cardiff University", chineseName: "卡迪夫大学", country: "英国", logo: "image/global-universities/Cardiff_University.png" },
    { rank: 182, name: "Emory University", chineseName: "埃默里大学", country: "美国", logo: "image/global-universities/Emory_University.png" },
    { rank: 183, name: "Curtin University", chineseName: "科廷大学", country: "澳大利亚", logo: "image/global-universities/Curtin_University.png" },
    { rank: 184, name: "University of Bern", chineseName: "伯尔尼大学", country: "瑞士", logo: "image/global-universities/University_of_Bern.png" },
    { rank: 184, name: "University of Wollongong", chineseName: "卧龙岗大学", country: "澳大利亚", logo: "image/global-universities/University_of_Wollongong.png" },
    { rank: 186, name: "Wuhan University", chineseName: "武汉大学", country: "中国", logo: "image/global-universities/Wuhan_University.png" },
    { rank: 187, name: "Tecnológico de Monterrey (ITESM)", chineseName: "蒙特雷科技学院", country: "墨西哥", logo: "image/global-universities/Tecnológico_de_Monterrey.png" },
    { rank: 187, name: "University Complutense Madrid", chineseName: "马德里康普顿斯大学", country: "西班牙", logo: "image/global-universities/University_Complutense_Madrid.png" },
    { rank: 189, name: "UNIVERSITAS INDONESIA", chineseName: "印度尼西亚大学", country: "印度尼西亚", logo: "image/global-universities/UNIVERSITAS_INDONESIA.png" },
    { rank: 190, name: "Ohio State University", chineseName: "俄亥俄州立大学", country: "美国", logo: "image/global-universities/Ohio_State_University.png" },
    { rank: 191, name: "Queen's University, Ontario", chineseName: "女王大学", country: "加拿大", logo: "image/global-universities/Queens_University_Ontario.png" },
    { rank: 191, name: "Université Catholique de Louvain (UCL)", chineseName: "天主教鲁汶大学", country: "比利时", logo: "image/global-universities/Université_Catholique_de_Louvain.png" },
    { rank: 193, name: "Universität Hamburg", chineseName: "汉堡大学", country: "德国", logo: "image/global-universities/Universität_Hamburg.png" },
    { rank: 194, name: "University of Reading", chineseName: "雷丁大学", country: "英国", logo: "image/global-universities/University_of_Reading.png" },
    { rank: 194, name: "Vrije Universiteit Amsterdam", chineseName: "阿姆斯特丹自由大学", country: "荷兰", logo: "image/global-universities/Vrije_Universiteit_Amsterdam.png" },
    { rank: 196, name: "Waseda University", chineseName: "早稻田大学", country: "日本", logo: "image/global-universities/Waseda_University.png" },
    { rank: 197, name: "University of Otago", chineseName: "奥塔哥大学", country: "新西兰", logo: "image/global-universities/University_of_Otago.png" },
    { rank: 197, name: "Vienna University of Technology", chineseName: "维也纳工业大学", country: "奥地利", logo: "image/global-universities/Vienna_University_of_Technology.png" },
    { rank: 199, name: "National Yang Ming Chiao Tung University", chineseName: "国立阳明交通大学", country: "中国台湾", logo: "image/global-universities/National_Yang_Ming_Chiao_Tung_University.png" },
    { rank: 199, name: "Queen's University Belfast", chineseName: "贝尔法斯特女王大学", country: "英国", logo: "image/global-universities/Queens_University_Belfast.png" }
];

// 辅助函数：根据排名获取大学信息
function getUniversityByRank(rank) {
    return QS_TOP_UNIVERSITIES.find(uni => uni.rank === rank);
}

// 辅助函数：根据英文名称获取大学信息
function getUniversityByName(name) {
    return QS_TOP_UNIVERSITIES.find(uni => uni.name === name);
}

// 辅助函数：根据国家/地区获取大学列表
function getUniversitiesByCountry(country) {
    return QS_TOP_UNIVERSITIES.filter(uni => uni.country === country);
}

// 辅助函数：根据中文名称获取大学信息
function getUniversityByChineseName(chineseName) {
    return QS_TOP_UNIVERSITIES.find(uni => uni.chineseName === chineseName);
}

// 导出数据（如果使用模块系统）
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        QS_TOP_UNIVERSITIES,
        getUniversityByRank,
        getUniversityByName,
        getUniversitiesByCountry,
        getUniversityByChineseName
    };
}
